name: Xcode - Integration Testing

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

env:
  PROJECT: embrace-outdoors-ios

jobs:
  xcode-test:
    timeout-minutes: 40
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode_version: ["15.4"]
        device:
          - "iPhone 15"
          - "iPhone 14 Plus"
          - "iPhone 13 Pro"
    steps:
      - name: Select Xcode
        # See https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app
          xcodebuild -version

      - name: Boot simulator
        run: |
          xcrun simctl boot "${{ matrix.device }}"
          xcrun simctl bootstatus "${{ matrix.device }}"

      - uses: actions/checkout@v4

      - name: Set Embrace appId
        run: |
          sed -i.bak 's/appId: ".*"/appId: "${{ vars.EMBRACE_APP_ID }}"/' iOS/${{ env.PROJECT }}/${{ env.PROJECT }}/App/EmbraceOutdoorsApp.swift

      - uses: actions/cache@v4
        with:
          path: build/
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('iOS/embrace-outdoors-ios/embrace-outdoors-ios.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      - name: xcodebuild test
        env:
          IS_XCTEST: true # Needed to disable SwiftLint -> SwiftSyntax plugin dependency build issue
        run: |
          (set -o pipefail && xcodebuild test -project "iOS/${{ env.PROJECT }}/${{ env.PROJECT }}.xcodeproj" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
          -scheme "${{ env.PROJECT }}" -derivedDataPath "build/DerivedData" -clonedSourcePackagesDirPath "build/" -destination "platform=iOS Simulator,name=${{ matrix.device }}" | xcpretty) || exit 0
